function import_ol = import_ol_csv(filename, dataLines)
%IMPORTFILE Import data from a text file
%  D181OL = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  D181OL = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  D181ol = importfile("C:\Users\jonat\Desktop\NWHR_Manuscript\git_repo\Geothermometry_Error_Analysis\MATLAB_Projects\Scripts_dump\D18_1_ol.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Aug-2022 15:53:51

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "SiO2", "FeO", "MgO", "CaO", "NiO", "MnO", "TOTAL", "Fo"];
opts.SelectedVariableNames = ["SiO2", "FeO", "MgO", "CaO", "NiO", "MnO", "TOTAL", "Fo"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2"], "EmptyFieldRule", "auto");

% Import the data
import_ol = readtable(filename, opts);

end